


const tribunalesPorCorte = {
    0: [
    ],
    10: [
      { value: "0", nombre: "Todos" },
      { value: "2", nombre: "1º Juzgado de Letras de Arica" },
      { value: "1400", nombre: "1º Juzgado De Letras de Arica ex 4°" },
      { value: "3", nombre: "2º Juzgado de Letras de Arica" },
      { value: "1401", nombre: "2º Juzgado De Letras de Arica ex 4°" },
      { value: "4", nombre: "3º Juzgado de Letras de Arica" },
      { value: "5", nombre: "3º Juzgado de Letras de Arica Ex 4º" }
    ],
    11: [
  
      { value: "0", nombre: "Todos" },
      { value: "6", nombre: "Juzgado de Letras y Gar. Pozo Almonte" },
      { value: "9", nombre: "1º Juzgado de Letras de Iquique" },
      { value: "10", nombre: "2º Juzgado de Letras de Iquique" },
      { value: "11", nombre: "3º Juzgado de Letras de Iquique" }
    ],
    15: [
      { value: "0", nombre: "Todos" },
      { value: "13", nombre: "Juzgado de Letras Tocopilla" },
      { value: "14", nombre: "Juzgado de Letras y Gar. de María Elena" },
      { value: "16", nombre: "1º Juzgado de Letras de Calama" },
      { value: "17", nombre: "2º Juzgado de Letras de Calama" },
      { value: "658", nombre: "3º Juzgado de Letras de Calama" },
      { value: "26", nombre: "Juzgado de Letras y Gar. de Taltal" },
      { value: "1041", nombre: "1º Juzgado de Letras Civil de Antofagasta" },
      { value: "1042", nombre: "2º Juzgado de Letras Civil de Antofagasta" },
      { value: "1043", nombre: "3º Juzgado de Letras Civil de Antofagasta" },
      { value: "1044", nombre: "4° Juzgado de Letras Civil de Antofagasta" },
      { value: "1501", nombre: "Juzgado de Letras y Garantía Mejillones" }
  
    ],
    20: [
      { value: '0', nombre: 'Todos' },
      { value: '27', nombre: 'Juzgado de Letras y Gar. de Chañaral' },
      { value: '29', nombre: 'Juzgado de Letras de Diego de Almagro' },
      { value: '31', nombre: '1º Juzgado de Letras de Copiapó' },
      { value: '32', nombre: '2º Juzgado de Letras de Copiapó' },
      { value: '33', nombre: '3º Juzgado de Letras de Copiapó' },
      { value: '34', nombre: 'Juzgado de Letras y Gar.de Freirina' },
      { value: '926', nombre: '4º Juzgado de Letras de Copiapó' },
      { value: '36', nombre: '1º Juzgado de Letras de Vallenar' },
      { value: '37', nombre: '2º Juzgado de Letras de Vallenar' },
      { value: '386', nombre: 'Juzgado de Letras y Gar.de Caldera' }
    ],
    25: [
      { value: '0', nombre: 'Todos' },
      { value: '40', nombre: '1º Juzgado de Letras de la Serena' },
      { value: '41', nombre: '2º Juzgado de Letras de la Serena' },
      { value: '42', nombre: '3º Juzgado de Letras de la Serena' },
      { value: '43', nombre: '1º Juzgado de Letras de Coquimbo' },
      { value: '44', nombre: '2º Juzgado de Letras de Coquimbo' },
      { value: '45', nombre: '3º Juzgado de Letras de Coquimbo' },
      { value: '46', nombre: 'Juzgado de Letras de Vicuña' },
      { value: '47', nombre: 'Juzgado de letras y garantía de Andacollo' },
      { value: '48', nombre: '1º Juzgado de Letras de Ovalle' },
      { value: '49', nombre: '2º Juzgado de Letras de Ovalle' },
      { value: '50', nombre: '3º Juzgado de Letras de Ovalle' },
      { value: '51', nombre: 'Juzgado de Letras y Gar.de Combarbalá' },
      { value: '52', nombre: 'Juzgado de Letras de Illapel' },
      { value: '53', nombre: 'Juzgado de Letras y Gar. de los Vilos' }
    ],
    30: [
      { value: '0', nombre: 'Todos' },
      { value: '56', nombre: '1º Juzgado Civil de Valparaíso' },
      { value: '55', nombre: '2º Juzgado Civil de Valparaíso' },
      { value: '54', nombre: '3º Juzgado Civil de Valparaíso' },
      { value: '59', nombre: '4º Juzgado Civil de Valparaíso' },
      { value: '60', nombre: '5º Juzgado Civil de Valparaíso' },
      { value: '57', nombre: '1º Juzgado Civil de Viña del Mar' },
      { value: '58', nombre: '2º Juzgado Civil de Viña del Mar' },
      { value: '61', nombre: '3º Juzgado Civil de Viña del Mar' },
      { value: '83', nombre: '1º Juzgado de Letras de Quilpue' },
      { value: '84', nombre: '2º Juzgado de Letras de Quilpue' },
      { value: '85', nombre: 'Juzgado de Letras de Villa Alemana' },
      { value: '86', nombre: 'Juzgado de Letras de Casablanca' },
      { value: '87', nombre: 'Juzgado de Letras de La Ligua' },
      { value: '88', nombre: 'Juzgado de Letras y Gar. de Petorca' },
      { value: '89', nombre: '1º Juzgado de Letras de Los Andes' },
      { value: '90', nombre: '2º Juzgado de Letras de Los Andes' },
      { value: '92', nombre: '1º Juzgado de Letras de San Felipe' },
      { value: '93', nombre: '1º Juzgado de Letras de San Felipe Ex 2º' },
      { value: '94', nombre: 'Juzgado de Letras y Gar.de Putaendo' },
      { value: '96', nombre: '1º Juzgado de Letras de Quillota' },
      { value: '97', nombre: '2º Juzgado de Letras de Quillota' },
      { value: '98', nombre: 'Juzgado de Letras de La Calera' },
      { value: '99', nombre: 'Juzgado de Letras de Limache' },
      { value: '101', nombre: '1º Juzgado de Letras de San Antonio' },
      { value: '102', nombre: '2º Juzgado de Letras de San Antonio' },
      { value: '103', nombre: 'Juzgado de Letras y Gar. de Isla de Pascua' },
      { value: '660', nombre: 'Juzgado de Letras y Gar.de Quintero' }
    ],
    35: [
      { value: '0', nombre: 'Todos' },
      { value: '110', nombre: '1º Juzgado Civil de Rancagua' },
      { value: '969', nombre: '2º Juzgado Civil de Rancagua' },
      { value: '111', nombre: '1º Juzgado de Letras de Rengo' },
      { value: '113', nombre: 'Juzgado de Letras de San Vicente de Tagua Tagua' },
      { value: '114', nombre: '1º Juzgado de Letras y Gar.de Peumo' },
      { value: '115', nombre: '1º Juzgado de Letras de San Fernando' },
      { value: '116', nombre: '2º Juzgado de Letras de San Fernando' },
      { value: '117', nombre: '1º Juzgado de Letras de Santa Cruz' },
      { value: '118', nombre: '1º Juzgado De Letras De Santa Cruz Ex 2°' },
      { value: '119', nombre: 'Juzgado de Letras y Gar.de Pichilemu' },
      { value: '1150', nombre: 'Juzgado de Letras y Gar.de Litueche' },
      { value: '1151', nombre: 'Juzgado de Letras y Gar.de Peralillo' }
    ],
    40: [
      { value: '0', nombre: 'Todos' },
      { value: '122', nombre: '1º Juzgado de Letras de Talca' },
      { value: '123', nombre: '2º Juzgado de Letras de Talca' },
      { value: '124', nombre: '3º Juzgado de Letras de Talca' },
      { value: '125', nombre: '4º Juzgado de Letras de Talca' },
      { value: '126', nombre: 'Juzgado de Letras de Constitución' },
      { value: '127', nombre: 'Juzgado De Letras Y Gar. de Curepto' },
      { value: '129', nombre: '1º Juzgado de Letras de Curicó' },
      { value: '130', nombre: '2º Juzgado de Letras de Curicó' },
      { value: '131', nombre: '2º Juzgado de Letras de Curicó Ex 3°' },
      { value: '132', nombre: 'Juzgado De Letras Y Gar. de Licantén' },
      { value: '133', nombre: 'Juzgado de Letras de Molina' },
      { value: '135', nombre: '1º Juzgado de Letras de Linares' },
      { value: '136', nombre: '2º Juzgado de Letras de Linares' },
      { value: '138', nombre: 'Juzgado de Letras de San Javier' },
      { value: '139', nombre: 'Juzgado de Letras de Cauquenes' },
      { value: '140', nombre: 'Juzgado de Letras y Gar. de Chanco' },
      { value: '141', nombre: 'Juzgado de Letras de Parral' }
    ],
    45: [
      { value: '0', nombre: 'Todos' },
      { value: '145', nombre: '1º Juzgado Civil de Chillán' },
      { value: '146', nombre: '2º Juzgado Civil de Chillán' },
      { value: '147', nombre: '1º Juzgado de Letras de San Carlos' },
      { value: '149', nombre: 'Juzgado de Letras de Yungay' },
      { value: '150', nombre: 'Juzgado de Letras y Gar. de Bulnes' },
      { value: '151', nombre: 'Juzgado de Letras y Gar.de Coelemu' },
      { value: '152', nombre: 'Juzgado de Letras y Gar.de Quirihue' }
    ],
    46: [
      { value: '0', nombre: 'Todos' },
      { value: '154', nombre: '1º Juzgado de Letras de Los Angeles' },
      { value: '155', nombre: '2º Juzgado de Letras de Los Angeles' },
      { value: '156', nombre: '2° Juzgado de Letras de Los Angeles ex 3°' },
      { value: '157', nombre: 'Juzgado de Letras y Gar. de Mulchen' },
      { value: '158', nombre: 'Juzgado de Letras y Gar.de Nacimiento' },
      { value: '159', nombre: 'Juzgado de Letras y Gar.de Laja' },
      { value: '160', nombre: 'Juzgado de Letras y Gar.de Yumbel' },
      { value: '161', nombre: '1º Juzgado Civil de Concepción' },
      { value: '162', nombre: '2º Juzgado Civil de Concepción' },
      { value: '163', nombre: '3º Juzgado Civil de Concepción' },
      { value: '179', nombre: '1º Juzgado Civil de Talcahuano' },
      { value: '180', nombre: '2º Juzgado Civil de Talcahuano' },
      { value: '187', nombre: 'Juzgado de Letras de Tomé' },
      { value: '188', nombre: 'Juzgado de Letras y Gar.de Florida' },
      { value: '189', nombre: 'Juzgado de Letras y Gar.de Santa Juana' },
      { value: '190', nombre: 'Juzgado de Letras y Gar. de Lota' },
      { value: '191', nombre: '1º Juzgado de Letras de Coronel' },
      { value: '192', nombre: '2º Juzgado de Letras de Coronel' },
      { value: '193', nombre: 'Juzgado de Letras y Gar.de Lebu' },
      { value: '194', nombre: 'Juzgado de Letras de Arauco' },
      { value: '195', nombre: 'Juzgado de Letras y Gar.de Curanilahue' },
      { value: '196', nombre: 'Juzgado de Letras de Cañete' },
      { value: '385', nombre: 'Juzgado de Letras y Gar. Santa Bárbara' },
      { value: '1152', nombre: 'Juzgado de Letras y Gar.de Cabrero' }
    ],
    50: [
      { value: '0', nombre: 'Todos' },
      { value: '197', nombre: '1º Juzgado Civil de Temuco' },
      { value: '198', nombre: '2º Juzgado Civil de Temuco' },
      { value: '204', nombre: 'Juzgado de Letras de Angol' },
      { value: '206', nombre: 'Juzgado de Letras y Gar.de Collipulli' },
      { value: '207', nombre: 'Juzgado de Letras y Gar.de Traiguén' },
      { value: '208', nombre: 'Juzgado de Letras de Victoria' },
      { value: '209', nombre: 'Juzgado de Letras y Gar.de Curacautin' },
      { value: '210', nombre: 'Juzgado de Letras Loncoche' },
      { value: '211', nombre: 'Juzgado de Letras de Pitrufquen' },
      { value: '212', nombre: 'Juzgado de Letras de Villarrica' },
      { value: '213', nombre: 'Juzgado de Letras de Nueva Imperial' },
      { value: '214', nombre: 'Juzgado de Letras y Gar.de Pucón' },
      { value: '215', nombre: 'Juzgado de Letras de Lautaro' },
      { value: '216', nombre: 'Juzgado de Letras y Gar.de Carahue' },
      { value: '406', nombre: '3º Juzgado Civil de Temuco' },
      { value: '946', nombre: 'Juzgado de Letras y Gar.de Tolten' },
      { value: '947', nombre: 'Juzgado de Letras y Gar.de Puren' }
    ],
    55: [
      { value: '0', nombre: 'Todos' },
      { value: '220', nombre: '1º Juzgado Civil de Valdivia' },
      { value: '221', nombre: '2º Juzgado Civil de Valdivia' },
      { value: '222', nombre: 'Juzgado de Letras de Mariquina' },
      { value: '223', nombre: 'Juzgado de Letras y Gar.de Paillaco' },
      { value: '224', nombre: 'Juzgado de Letras Los Lagos' },
      { value: '225', nombre: 'Juzgado de Letras y Gar. de Panguipulli' },
      { value: '226', nombre: 'Juzgado de Letras y Gar.de la Unión' },
      { value: '227', nombre: 'Juzgado de Letras y Gar.de Río Bueno' },
      { value: '229', nombre: '1º Juzgado de Letras de Osorno' },
      { value: '230', nombre: '2º Juzgado de Letras de Osorno' },
      { value: '233', nombre: 'Juzgado de Letras de Rio Negro' }
    ],
    56: [
      { value: '0', nombre: 'Todos' },
      { value: '237', nombre: '1º Juzgado Civil de Puerto Montt' },
      { value: '1012', nombre: '2º Juzgado Civil de Puerto Montt' },
      { value: '238', nombre: 'Juzgado de Letras de Puerto Varas' },
      { value: '240', nombre: 'Juzgado de Letras y Gar.de Calbuco' },
      { value: '241', nombre: 'Juzgado de Letras y Gar. de Maullin' },
      { value: '242', nombre: 'Juzgado de Letras de Castro' },
      { value: '243', nombre: 'Juzgado de Letras de Ancud' },
      { value: '244', nombre: 'Juzgado de Letras y Garantía de Achao' },
      { value: '245', nombre: 'Juzgado de Letras y Gar. de Chaitén' },
      { value: '659', nombre: 'Juzgado de Letras y Gar. de Los Muermos' },
      { value: '662', nombre: 'Juzgado de Letras y Gar. de Quellón' },
      { value: '1013', nombre: 'Juzgado de Letras y Gar. de Hualaihue' }
    ],
    60: [
      { value: '0', nombre: 'Todos' },
      { value: '246', nombre: '1º Juzgado de Letras de Coyhaique' },
      { value: '247', nombre: '1º Juzgado de Letras de Coyhaique Ex 2º' },
      { value: '248', nombre: 'Juzgado de Letras y Gar.de pto.Aysen' },
      { value: '249', nombre: 'Juzgado de Letras y Gar.de Chile Chico' },
      { value: '250', nombre: 'Juzgado de Letras y Gar.de Cochrane' },
      { value: '996', nombre: 'Juzgado de Letras y Gar.de Puerto Cisnes' }
    ],
    61: [
      { value: '0', nombre: 'Todos' },
      { value: '253', nombre: '1º Juzgado de Letras de Punta Arenas' },
      { value: '254', nombre: '2º Juzgado de Letras de Punta Arenas' },
      { value: '255', nombre: '3º Juzgado de Letras de Punta Arenas' },
      { value: '257', nombre: 'Juzgado de Letras y Gar. de Puerto Natales' },
      { value: '258', nombre: 'Juzgado de Letras y Gar.de Porvenir' },
      { value: '1502', nombre: 'Juzgado de Letras y Garantía de Cabo de Hornos' }
    ],
    90: [
      { value: '0', nombre: 'Todos' },
      { value: '259', nombre: '1º Juzgado Civil de Santiago' },
      { value: '260', nombre: '2º Juzgado Civil de Santiago' },
      { value: '261', nombre: '3º Juzgado Civil de Santiago' },
      { value: '262', nombre: '4º Juzgado Civil de Santiago' },
      { value: '263', nombre: '5º Juzgado Civil de Santiago' },
      { value: '264', nombre: '6º Juzgado Civil de Santiago' },
      { value: '265', nombre: '7º Juzgado Civil de Santiago' },
      { value: '266', nombre: '8º Juzgado Civil de Santiago' },
      { value: '267', nombre: '9º Juzgado Civil de Santiago' },
      { value: '268', nombre: '10º Juzgado Civil de Santiago' },
      { value: '269', nombre: '11º Juzgado Civil de Santiago' },
      { value: '270', nombre: '12º Juzgado Civil de Santiago' },
      { value: '271', nombre: '13º Juzgado Civil de Santiago' },
      { value: '272', nombre: '14º Juzgado Civil de Santiago' },
      { value: '273', nombre: '15º Juzgado Civil de Santiago' },
      { value: '274', nombre: '16º Juzgado Civil de Santiago' },
      { value: '275', nombre: '17º Juzgado Civil de Santiago' },
      { value: '276', nombre: '18º Juzgado Civil de Santiago' },
      { value: '277', nombre: '19º Juzgado Civil de Santiago' },
      { value: '278', nombre: '20º Juzgado Civil de Santiago' },
      { value: '279', nombre: '21º Juzgado Civil de Santiago' },
      { value: '280', nombre: '22º Juzgado Civil de Santiago' },
      { value: '281', nombre: '23º Juzgado Civil de Santiago' },
      { value: '282', nombre: '24º Juzgado Civil de Santiago' },
      { value: '283', nombre: '25º Juzgado Civil de Santiago' },
      { value: '284', nombre: '26º Juzgado Civil de Santiago' },
      { value: '285', nombre: '27º Juzgado Civil de Santiago' },
      { value: '286', nombre: '28º Juzgado Civil de Santiago' },
      { value: '287', nombre: '29º Juzgado Civil de Santiago' },
      { value: '288', nombre: '30º Juzgado Civil de Santiago' },
      { value: '387', nombre: 'Juzgado de Letras de Colina' }
    ],
    91: [
      { value: '0', nombre: 'Todos' },
      { value: '343', nombre: '1º Juzgado Civil de San Miguel' },
      { value: '344', nombre: '2º Juzgado Civil de San Miguel' },
      { value: '345', nombre: '3º Juzgado Civil de San Miguel' },
      { value: '390', nombre: '4º Juzgado Civil de San Miguel' },
      { value: '364', nombre: '1º Juzgado Civil de Puente Alto' },
      { value: '373', nombre: '1º Juzgado De Letras De Talagante' },
      { value: '374', nombre: '2º Juzgado De Letras De Talagante' },
      { value: '375', nombre: '1º Juzgado de Letras de Melipilla' },
      { value: '377', nombre: '1º Juzgado de Letras de Buin' },
      { value: '378', nombre: '2º Juzgado de Letras de Buin' },
      { value: '388', nombre: 'Juzgado de Letras de Peñaflor' },
      { value: '400', nombre: '1º Juzgado de Letras de San Bernardo' },
      { value: '1402', nombre: '1º Juzgado de Letras de San Bernardo Ex 3°' },
      { value: '401', nombre: '2º Juzgado de Letras de San Bernardo' },
      { value: '1403', nombre: '2º Juzgado de Letras de San Bernardo Ex 3°' }
    ],
  }

module.exports = {tribunalesPorCorte}